owner: Me-Phew
repo: timetable-uptime

sites:
  - name: Timetable
    url: https://timetable.dripsiaga.pl/
  - name: API
    url: https://api.timetable.dripsiaga.pl/docs
    icon: https://raw.githubusercontent.com/Me-Phew/timetable-uptime/master/assets/server.svg

status-website:
  baseUrl: /timetable-uptime
  favicon: https://raw.githubusercontent.com/Me-Phew/timetable-uptime/master/assets/favicon.ico
  logoUrl: https://raw.githubusercontent.com/Me-Phew/timetable-uptime/master/assets/android-chrome-192x192.png
  name: MePhew Timetable Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
  user-agent: $OWNER
